cc_library(
  name = "common",
  srcs = [
  ],
  hdrs = [
    "net.h",
  ],
  includes = [
    "."
  ],
  copts = [
    "-std=c++17",
  ],
  deps = [
    "//3rdparty/asio:asio",
  ],
  visibility = [
    "//visibility:public",
  ],
)
